name: "build-test"
on: [push]

jobs:
  test_something:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: patcito/diff-action@v0.2.1
        with:
          old: README.md
          new: README.md
          mode: addition
          tolerance: same
          output: out.txt
#name: Pull Request Action
#on: push
#jobs:
#  JobName1:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#        with:
#          fetch-depth: 0
#      - name: Foo Bars
#        run: |
#          git fetch
#          git diff origin/main HEAD | grep slippage
#          node test.js
#        shell: bash
