name: "build-test"
on: [push]

jobs:
  test_something:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: patcito/check-keywords-in-diff@v0.2.60
        with:
          branch: main
          notify_issue: true
          title: payment related code
          token: ${{ secrets.GITHUB_TOKEN }}
